access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  rabbitmq:
    addresses: ${RABBIT_HOST}:${RABBIT_PORT}
  profiles:
    active: dev
  data:
    mongodb:
      uri: "mongodb+srv://tesis:tesis@cluster0.hccq1nc.mongodb.net/Users"

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081










